# -*- coding: utf-8 -*-
"""Section 1: Data Pipelines.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ixz7tO893n6CVhiGVcTwLc_A6GdJm8ME
"""

# importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read the dataset1.csv and dataset2.csv file
dataset1 = pd.read_csv('dataset1.csv')
dataset2 = pd.read_csv('dataset2.csv')

# show first 5 rows of dataset1
dataset1.head()

# show first 5 rows of dataset2
dataset2.head()

# show the shapes of dataset1 and dataset2
print(f"Shape of dataset1 is {dataset1.shape}")
print(f"Shape of dataset2 is {dataset2.shape}")

# Preprocessing 1: Split the name field into first_name, and last_name
# We will split() the name and take the first split word as first name and the last split word as last name

# For dataset 1
dataset1.loc[dataset1['name'].str.split().str.len() == 2, 'first name'] = dataset1['name'].str.split().str[0]
dataset1.loc[dataset1['name'].str.split().str.len() == 2, 'last name'] = dataset1['name'].str.split().str[-1]

print(f"After spliting name into first and last name, dataset1: \n\n {dataset1.head()}")

# For dataset 2
dataset2.loc[dataset2['name'].str.split().str.len() == 2, 'first name'] = dataset2['name'].str.split().str[0]
dataset2.loc[dataset2['name'].str.split().str.len() == 2, 'last name'] = dataset2['name'].str.split().str[-1]

print(f"\n\nAfter spliting name into first and last name, dataset1: \n\n {dataset2.head()}")

dataset1.dtypes

dataset2.dtypes

# Preprocessing 2: Remove any zeros prepended to the price field

# Convert the price column to string and then remove any prepend zeros
dataset1["price"] = dataset1["price"].astype('str')
dataset2["price"] = dataset2["price"].astype('str')

dataset1["price"] = dataset1["price"].str.lstrip('0')
dataset2["price"] = dataset2["price"].str.lstrip('0')

# Preprocessing 3: Delete any rows which do not have a name
# We will drop null values for the column 'name'

dataset1 = dataset1.dropna(axis=0, subset=['name'])
dataset2 = dataset2.dropna(axis=0, subset=['name'])

# Preprocessing 4: Create a new field named above_100, which is true if the price is strictly greater than 100
# We will use numpy where to filter values geater than 100 and assign it to True for the new column

print(f"Checking dtypes of Price column in both dataset: \n\n")
print(f"dataset1 dtypes:\n {dataset1.dtypes}\n\n")
print(f"dataset2 dtypes: \n{dataset2.dtypes}\n\n")

print(f"Changing dtype of dataset1['price'] and dataset2['price'] to float64\n\n")
dataset1["price"] = dataset1.price.astype("float64")
dataset2["price"] = dataset2.price.astype("float64")

dataset1['above_100'] = np.where(dataset1['price'] > 100.0, True, False)
dataset2['above_100'] = np.where(dataset2['price'] > 100.0, True, False)

print(f"conversion finished")

# printing both datasets after processing

print(f"dataset1:\n\n {dataset1.head(10)}")
print(f"\ndataset2:\n\n {dataset2.head(10)}")

# Saving the processed files
dataset1.to_csv("processed_dataset1.csv", index=False)
dataset2.to_csv("processed_dataset2.csv", index=False)

